server:
  port: 8080
  address: 127.0.0.1

spring:
  application:
    name: QuestAi
  elasticsearch:
    uris: http://localhost:9200


app:
  #embedding-model:
    #name: zhipu-embedding-2
    #api-key: 22222222-2222-2222-2222-222222222222
  document-splitter: sentence-document-splitter
  embedding-store: elastic-search-store

